 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: 
      - '-c'
      - cat <<< "$$PASSWORD" | docker login --username="$$USERNAME" --password-stdin
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/agones-example-minetest:5.9.0 .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/agones-example-minetest:5.9.0']
   secretEnv: ['USERNAME']
 availableSecrets:
   secretManager:
   - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
     env: 'USERNAME'